package com.moodbuds.admin;

import com.moodbuds.common.PageResponse;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/admin")
public class AdminReportingController {private final JdbcClient jdbc;public AdminReportingController(JdbcClient jdbc){this.jdbc=jdbc;}
 @GetMapping("/dashboard") @PreAuthorize("hasAuthority('reports.read') or hasRole('SUPER_ADMIN')") Object dashboard(){return java.util.Map.of("orders",jdbc.sql("SELECT COUNT(*) count,COALESCE(SUM(total_amount),0) total_amount FROM orders").query().singleRow(),"customers",jdbc.sql("SELECT COUNT(*) count FROM users").query().singleRow(),"products",jdbc.sql("SELECT COUNT(*) count,SUM(is_active=1) active_count FROM products").query().singleRow(),"returns",jdbc.sql("SELECT COUNT(*) count,SUM(status NOT IN ('COMPLETED','CLOSED','REJECTED')) open_count FROM return_requests").query().singleRow(),"lowStock",jdbc.sql("SELECT COUNT(*) count FROM product_sizes WHERE stock_quantity<=low_stock_threshold").query().singleRow());}
 @GetMapping("/reports/sales") @PreAuthorize("hasAuthority('reports.read') or hasRole('SUPER_ADMIN')") Object sales(@RequestParam(required=false)String from,@RequestParam(required=false)String to){String w=" WHERE (:from IS NULL OR created_at>=:from) AND (:to IS NULL OR created_at<DATEADD('DAY', 1, :to))";return jdbc.sql("SELECT DATE(created_at) sale_date,COUNT(*) order_count,SUM(subtotal) subtotal,SUM(coupon_discount) discounts,SUM(gst_amount) gst,SUM(shipping_cost) shipping,SUM(total_amount) total FROM orders"+w+" GROUP BY DATE(created_at) ORDER BY sale_date DESC").param("from",from).param("to",to).query().listOfRows();}
 @GetMapping("/reports/gst") @PreAuthorize("hasAuthority('reports.read') or hasRole('SUPER_ADMIN')") Object gst(@RequestParam(required=false)String from,@RequestParam(required=false)String to){return jdbc.sql("SELECT invoice_date,invoice_number,order_id,customer_name,customer_gstin,subtotal,cgst_amount,sgst_amount,igst_amount,total_tax,total_amount FROM gst_invoices WHERE (:from IS NULL OR invoice_date>=:from) AND (:to IS NULL OR invoice_date<=:to) ORDER BY invoice_date DESC").param("from",from).param("to",to).query().listOfRows();}
 @GetMapping("/reports/inventory") @PreAuthorize("hasAuthority('reports.read') or hasRole('SUPER_ADMIN')") Object inventory(){return jdbc.sql("SELECT p.id,p.sku,p.name,ps.size,ps.stock_quantity,ps.low_stock_threshold,ps.is_available FROM products p JOIN product_sizes ps ON ps.product_id=p.id ORDER BY p.name,ps.id").query().listOfRows();}
 @GetMapping("/activity-logs") @PreAuthorize("hasAuthority('audit.read') or hasRole('SUPER_ADMIN')") Object audit(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){int s=Math.min(Math.max(size,1),100),p=Math.max(page,0);var rows=jdbc.sql("SELECT l.*,u.username admin_username FROM admin_activity_logs l JOIN admin_users u ON u.id=l.admin_user_id ORDER BY l.id DESC LIMIT :limit OFFSET :offset").param("limit",s).param("offset",p*s).query().listOfRows();long count=jdbc.sql("SELECT COUNT(*) FROM admin_activity_logs").query(Long.class).single();return PageResponse.of(rows,p,s,count);}}
