package com.moodbuds.admin;

import java.util.Map;import com.moodbuds.audit.AuditService;import com.moodbuds.auth.CurrentAdmin;import com.moodbuds.common.ApiException;import com.moodbuds.common.PageResponse;
import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/admin/customers")
public class CustomerAdminController {private final JdbcClient jdbc;private final AuditService audit;public CustomerAdminController(JdbcClient jdbc,AuditService audit){this.jdbc=jdbc;this.audit=audit;}
 @GetMapping @PreAuthorize("hasAuthority('customers.read') or hasRole('SUPER_ADMIN')") Object list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false,name="q")String q){int s=Math.min(Math.max(size,1),100),p=Math.max(page,0);String w=q==null||q.isBlank()?"":" WHERE email LIKE :q OR mobile LIKE :q OR first_name LIKE :q OR last_name LIKE :q";var query=jdbc.sql("SELECT id,email,mobile,mobile_verified,email_verified,first_name,last_name,date_of_birth,gender,is_active,last_login_at,created_at,updated_at FROM users"+w+" ORDER BY id DESC LIMIT :limit OFFSET :offset").param("limit",s).param("offset",p*s);var count=jdbc.sql("SELECT COUNT(*) FROM users"+w);if(!w.isEmpty()){query=query.param("q","%"+q+"%");count=count.param("q","%"+q+"%");}return PageResponse.of(query.query().listOfRows(),p,s,count.query(Long.class).single());}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('customers.read') or hasRole('SUPER_ADMIN')") Object get(@PathVariable long id){var r=new java.util.LinkedHashMap<>(jdbc.sql("SELECT id,email,mobile,mobile_verified,email_verified,first_name,last_name,date_of_birth,gender,is_active,last_login_at,created_at,updated_at FROM users WHERE id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->ApiException.notFound("Customer")));r.put("addresses",jdbc.sql("SELECT * FROM user_addresses WHERE user_id=:id ORDER BY is_default DESC,id").param("id",id).query().listOfRows());r.put("orderCount",jdbc.sql("SELECT COUNT(*) FROM orders WHERE user_id=:id").param("id",id).query(Long.class).single());return r;}
 @PatchMapping("/{id}/status") @PreAuthorize("hasAuthority('customers.manage') or hasRole('SUPER_ADMIN')") Object status(@PathVariable long id,@RequestBody Map<String,Boolean> body,@AuthenticationPrincipal Jwt jwt){Boolean active=body.get("active");if(active==null)throw ApiException.badRequest("ACTIVE_REQUIRED","active is required");if(jdbc.sql("UPDATE users SET is_active=:active,updated_at=CURRENT_TIMESTAMP() WHERE id=:id").param("active",active).param("id",id).update()==0)throw ApiException.notFound("Customer");audit.record(CurrentAdmin.id(jwt),"customer.status_updated","user",id,null,body);return get(id);}}
