package com.moodbuds.admin;

import java.util.Map;import java.util.Set;
import com.moodbuds.audit.AuditService;import com.moodbuds.auth.CurrentAdmin;import com.moodbuds.common.ApiException;import com.moodbuds.common.PageResponse;
import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/admin/returns")
public class ReturnAdminController {
 private static final Map<String,Set<String>> TRANSITIONS=Map.of("REQUESTED",Set.of("APPROVED","REJECTED"),"APPROVED",Set.of("PICKUP_SCHEDULED","ITEM_RECEIVED"),"PICKUP_SCHEDULED",Set.of("ITEM_RECEIVED"),"ITEM_RECEIVED",Set.of("QUALITY_CHECK_PASSED","QUALITY_CHECK_FAILED"),"QUALITY_CHECK_FAILED",Set.of("CLOSED"));
 private final JdbcClient jdbc;private final AuditService audit;public ReturnAdminController(JdbcClient jdbc,AuditService audit){this.jdbc=jdbc;this.audit=audit;}
 @GetMapping @PreAuthorize("hasAuthority('returns.read') or hasRole('SUPER_ADMIN')") Object list(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){int s=Math.min(Math.max(size,1),100),p=Math.max(page,0);String where=status==null||status.isBlank()?"":" WHERE rr.status=:status";var q=jdbc.sql("SELECT rr.*,o.order_number,CONCAT(u.first_name,' ',u.last_name) customer_name FROM return_requests rr JOIN orders o ON o.id=rr.order_id JOIN users u ON u.id=rr.user_id"+where+" ORDER BY rr.id DESC LIMIT :limit OFFSET :offset").param("limit",s).param("offset",p*s);var c=jdbc.sql("SELECT COUNT(*) FROM return_requests rr"+where);if(!where.isEmpty()){q=q.param("status",status);c=c.param("status",status);}return PageResponse.of(q.query().listOfRows(),p,s,c.query(Long.class).single());}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('returns.read') or hasRole('SUPER_ADMIN')") Object get(@PathVariable long id){var r=new java.util.LinkedHashMap<>(jdbc.sql("SELECT rr.*,o.order_number,CONCAT(u.first_name,' ',u.last_name) customer_name FROM return_requests rr JOIN orders o ON o.id=rr.order_id JOIN users u ON u.id=rr.user_id WHERE rr.id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->ApiException.notFound("Return request")));r.put("items",jdbc.sql("SELECT ri.*,oi.product_snapshot,oi.size,oi.unit_price FROM return_items ri JOIN order_items oi ON oi.id=ri.order_item_id WHERE ri.return_request_id=:id").param("id",id).query().listOfRows());return r;}
 @PatchMapping("/{id}/status") @PreAuthorize("hasAuthority('returns.manage') or hasRole('SUPER_ADMIN')") @Transactional Object status(@PathVariable long id,@RequestBody StatusChange body,@AuthenticationPrincipal Jwt jwt){var old=jdbc.sql("SELECT status FROM return_requests WHERE id=:id FOR UPDATE").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->ApiException.notFound("Return request"));String from=String.valueOf(old.get("status")),to=body.status().toUpperCase();if(!TRANSITIONS.getOrDefault(from,Set.of()).contains(to))throw ApiException.badRequest("INVALID_RETURN_TRANSITION","Return cannot move from "+from+" to "+to);if("QUALITY_CHECK_PASSED".equals(to)){long pending=jdbc.sql("SELECT COUNT(*) FROM return_items WHERE return_request_id=:id AND condition_on_receipt IS NULL").param("id",id).query(Long.class).single();if(pending>0)throw ApiException.badRequest("RETURN_INSPECTION_INCOMPLETE","Every returned item must be inspected before quality checking passes");}jdbc.sql("UPDATE return_requests SET status=:status,admin_notes=COALESCE(:notes,admin_notes),rejection_reason=CASE WHEN :status='REJECTED' THEN :reason ELSE rejection_reason END,updated_at=CURRENT_TIMESTAMP() WHERE id=:id").param("status",to).param("notes",body.notes()).param("reason",body.reason()).param("id",id).update();audit.record(CurrentAdmin.id(jwt),"return.status_updated","return_request",id,old,Map.of("status",to));return get(id);}
 public record StatusChange(String status,String notes,String reason){}
}
