import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AdminBadge, AdminBody, AdminModuleBar, AdminStats, AdminToggle } from '../components/AdminUI';
import { adminQuizService, type AdminSummary } from '../services/adminQuizService';
import { adminCouponService, type AdminCoupon, type CouponDraft, type CustomerChoice } from '../services/adminCouponService';
import { useToast } from '../../../app/providers/ToastProvider';

const EMPTY: CouponDraft = { code:'',description:'',type:'FLAT',discountValue:300,minOrderValue:149900,maxDiscountAmount:null,usageLimitGlobal:null,usageLimitPerUser:1,audienceType:'PUBLIC',firstOrderOnly:false,showOnHomepage:false,active:true,validFrom:new Date().toISOString(),validUntil:null,assignedUserIds:[] };
const money = (paise:number) => `₹${Math.round(paise/100).toLocaleString('en-IN')}`;
const dateInput = (value?:string|null) => value ? new Date(value).toISOString().slice(0,16) : '';
const titleStatus = (value:string) => value.charAt(0)+value.slice(1).toLowerCase();
function message(error:unknown){if(!(error instanceof Error))return 'The coupon desk hit a snag. Please try again.';try{const body=JSON.parse(error.message) as {detail?:string;message?:string};return body.detail||body.message||error.message;}catch{return error.message;}}

export function AdminCouponsPage() {
  const toast=useToast();
  const [admin,setAdmin]=useState<AdminSummary|null>(()=>adminQuizService.currentAdmin());
  const [coupons,setCoupons]=useState<AdminCoupon[]>([]);
  const [stats,setStats]=useState({activeCoupons:0,redemptionsLast30Days:0,discountLast30Days:0,topCode:null as string|null});
  const [editing,setEditing]=useState<AdminCoupon|'new'|null>(null);
  const [draft,setDraft]=useState<CouponDraft>(EMPTY);
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState('ALL');
  const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const [customerQuery,setCustomerQuery]=useState(''); const [customers,setCustomers]=useState<CustomerChoice[]>([]);
  const [assignmentLimit,setAssignmentLimit]=useState<number|null>(null); const [assignmentReason,setAssignmentReason]=useState(''); const [refundId,setRefundId]=useState<number|null>(null);
  const [assignmentDetailsTouched,setAssignmentDetailsTouched]=useState(false);

  const load=async()=>{setLoading(true);setError('');try{const [page,s]=await Promise.all([adminCouponService.list(),adminCouponService.stats()]);setCoupons(page.content);setStats(s);}catch(e){setError(message(e));}finally{setLoading(false);}};
  useEffect(()=>{if(admin)void load();},[admin]);
  const visible=useMemo(()=>coupons.filter(c=>(filter==='ALL'||c.status===filter)&&`${c.code} ${c.description||''}`.toLowerCase().includes(query.toLowerCase())),[coupons,filter,query]);

  const openNew=()=>{setEditing('new');setDraft({...EMPTY,validFrom:new Date().toISOString(),validUntil:new Date(Date.now()+30*86400000).toISOString()});setCustomers([]);setAssignmentLimit(null);setAssignmentReason('');setRefundId(null);setAssignmentDetailsTouched(false);setError('');};
  const openEdit=async(c:AdminCoupon)=>{setEditing(c);setDraft({code:c.code,description:c.description||'',type:c.type,discountValue:Number(c.discountValue),minOrderValue:c.minOrderValue,maxDiscountAmount:c.maxDiscountAmount??null,usageLimitGlobal:c.usageLimitGlobal??null,usageLimitPerUser:c.usageLimitPerUser,audienceType:c.audienceType,firstOrderOnly:c.firstOrderOnly,showOnHomepage:c.showOnHomepage,active:c.active,validFrom:c.validFrom,validUntil:c.validUntil??null,assignedUserIds:[]});setCustomers([]);setAssignmentLimit(null);setAssignmentReason('');setRefundId(null);setAssignmentDetailsTouched(false);setError('');if(c.audienceType==='ASSIGNED_USERS'){try{const a=await adminCouponService.assignments(c.id);const active=a.content.filter(x=>x.active);setDraft(d=>({...d,assignedUserIds:active.map(x=>x.userId)}));setCustomers(a.content.map(x=>({id:x.userId,email:x.customerEmail,firstName:x.customerName})));}catch(e){setError(message(e));}}};
  const findCustomers=async()=>{if(customerQuery.trim().length<2)return;try{const page=await adminCouponService.customers(customerQuery);setCustomers(current=>[...current,...page.content].filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i));}catch(e){setError(message(e));}};
  const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const payload={...draft,code:draft.code.trim().toUpperCase(),validFrom:new Date(draft.validFrom).toISOString(),validUntil:draft.validUntil?new Date(draft.validUntil).toISOString():null,usageLimitPerUser:draft.firstOrderOnly?1:draft.usageLimitPerUser,maxDiscountAmount:draft.type==='PERCENTAGE'?draft.maxDiscountAmount:null,assignedUserIds:draft.audienceType==='ASSIGNED_USERS'?draft.assignedUserIds:[]};const saved=editing==='new'?await adminCouponService.create(payload):await adminCouponService.update((editing as AdminCoupon).id,payload);if(assignmentDetailsTouched&&draft.audienceType==='ASSIGNED_USERS'&&(draft.assignedUserIds||[]).length){await Promise.all((draft.assignedUserIds||[]).map(userId=>adminCouponService.assign(saved.id,userId,{usageLimitOverride:assignmentLimit,assignedReason:assignmentReason,refundId})));}setCoupons(current=>editing==='new'?[saved,...current]:current.map(c=>c.id===saved.id?saved:c));setEditing(null);toast.success(`${saved.code} ${editing==='new'?'created':'updated'}.`);void load();}catch(x){setError(message(x));}finally{setSaving(false);}};
  const toggle=async(c:AdminCoupon)=>{if(!window.confirm(`${c.active?'Deactivate':'Activate'} ${c.code}? Applied carts will be revalidated at checkout.`))return;try{const next=await adminCouponService.status(c.id,!c.active);setCoupons(x=>x.map(v=>v.id===next.id?next:v));}catch(e){setError(message(e));}};

  if(!admin)return <><AdminModuleBar title="Coupons & Discounts" sub="Create targeted, public and first-order offers"/><AdminBody><div className="adm-card qadm-login-card"><div className="adm-card-body"><div className="qadm-login-copy"><div className="qadm-lock">🎟️</div><div><span className="qadm-eyebrow">Restricted workspace</span><h2>Admin access</h2><p>Sign in to manage coupon rules and customer assignments.</p></div></div><form className="qadm-login-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setLoading(true);setError('');try{setAdmin(await adminCouponService.login(String(f.get('username')),String(f.get('password'))));}catch(x){setError(message(x));}finally{setLoading(false);}}}><label className="adm-field"><span>Username</span><input name="username" required/></label><label className="adm-field"><span>Password</span><input name="password" type="password" required/></label>{error&&<div className="qadm-error">{error}</div>}<button className="adm-btn primary" disabled={loading}>{loading?'Opening…':'Open coupon desk'}</button></form></div></div></AdminBody></>;

  return <><AdminModuleBar title="Coupons & Discounts" sub="Control who can see and redeem each offer" actions={<div className="madm-actions"><button className="adm-btn" onClick={()=>{adminQuizService.logout();setAdmin(null);}}>Sign out</button><button className="adm-btn primary" onClick={openNew}>+ New coupon</button></div>}/><AdminBody>
    <AdminStats items={[{label:'Active coupons',value:stats.activeCoupons,icon:'🎟️'},{label:'Redemptions (30d)',value:stats.redemptionsLast30Days,icon:'✓'},{label:'Discount given (30d)',value:money(stats.discountLast30Days),icon:'₹'},{label:'Top code',value:stats.topCode||'—',icon:'✦'}]}/>
    <div className="madm-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search coupon code or description…"/><div className="madm-filters">{['ALL','ACTIVE','SCHEDULED','EXPIRED','EXHAUSTED','INACTIVE'].map(x=><button type="button" key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x.toLowerCase()}</button>)}</div></div>
    {error&&!editing&&<div className="qadm-error">{error}</div>}{loading&&coupons.length===0?<div className="badm-loading">Counting the savings…</div>:<div className="cadm-grid">{visible.map(c=><article className={`cadm-card${c.active?'':' inactive'}`} key={c.id}><div className="cadm-card-head"><div><div className="adm-coupon-code">{c.code}</div><span>{c.audienceType==='PUBLIC'?'Everyone':c.audienceType==='PRIVATE_CODE'?'Private code':`${c.assignedUserCount} assigned`}</span></div><AdminBadge status={titleStatus(c.status)}/></div><p>{c.description||'No customer description'}</p><strong>{c.type==='FLAT'?`${money(Number(c.discountValue)*100)} off`:`${c.discountValue}% off${c.maxDiscountAmount?` · max ${money(c.maxDiscountAmount)}`:''}`}</strong><div className="cadm-rules"><span>Min {money(c.minOrderValue)}</span><span>{c.currentUsageCount}/{c.usageLimitGlobal??'∞'} used</span><span>{c.usageLimitPerUser}/customer</span>{c.firstOrderOnly&&<span>First order</span>}{c.showOnHomepage&&<span>Homepage</span>}</div><div className="cadm-card-foot"><AdminToggle on={c.active} onToggle={()=>void toggle(c)}/><button type="button" className="adm-btn ghost" onClick={()=>void openEdit(c)}>Edit</button></div></article>)}</div>}
    {editing&&<div className="madm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null);}}><form className="madm-modal cadm-modal" onSubmit={e=>void save(e)}><div className="madm-modal-head"><div><span className="qadm-eyebrow">Coupon rules</span><h2>{editing==='new'?'Create coupon':`Edit ${editing.code}`}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className="madm-form-grid">
      <label className="adm-field"><span>Code *</span><input value={draft.code} maxLength={50} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})} required/></label><label className="adm-field"><span>Audience *</span><select value={draft.audienceType} onChange={e=>setDraft({...draft,audienceType:e.target.value as CouponDraft['audienceType'],showOnHomepage:e.target.value==='PUBLIC'&&draft.showOnHomepage})}><option value="PUBLIC">Everyone</option><option value="PRIVATE_CODE">Private code</option><option value="ASSIGNED_USERS">Selected customers</option></select></label>
      <label className="adm-field madm-span"><span>Customer description</span><textarea value={draft.description} maxLength={500} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="adm-field"><span>Discount type</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as CouponDraft['type']})}><option value="FLAT">Flat amount</option><option value="PERCENTAGE">Percentage</option></select></label><label className="adm-field"><span>{draft.type==='FLAT'?'Discount ₹':'Discount %'} *</span><input type="number" min="0.01" step="0.01" value={draft.discountValue} onChange={e=>setDraft({...draft,discountValue:Number(e.target.value)})}/></label>
      <label className="adm-field"><span>Minimum order ₹</span><input type="number" min="0" value={draft.minOrderValue/100} onChange={e=>setDraft({...draft,minOrderValue:Math.round(Number(e.target.value)*100)})}/></label>{draft.type==='PERCENTAGE'&&<label className="adm-field"><span>Maximum discount ₹</span><input type="number" min="1" value={(draft.maxDiscountAmount||0)/100} onChange={e=>setDraft({...draft,maxDiscountAmount:e.target.value?Math.round(Number(e.target.value)*100):null})}/></label>}
      <label className="adm-field"><span>Global uses <small>blank = unlimited</small></span><input type="number" min="1" value={draft.usageLimitGlobal??''} onChange={e=>setDraft({...draft,usageLimitGlobal:e.target.value?Number(e.target.value):null})}/></label><label className="adm-field"><span>Uses per customer</span><input type="number" min="1" disabled={draft.firstOrderOnly} value={draft.firstOrderOnly?1:draft.usageLimitPerUser} onChange={e=>setDraft({...draft,usageLimitPerUser:Number(e.target.value)})}/></label>
      <label className="adm-field"><span>Valid from</span><input type="datetime-local" value={dateInput(draft.validFrom)} onChange={e=>setDraft({...draft,validFrom:e.target.value})}/></label><label className="adm-field"><span>Valid until <small>blank = no expiry</small></span><input type="datetime-local" value={dateInput(draft.validUntil)} onChange={e=>setDraft({...draft,validUntil:e.target.value||null})}/></label>
    </div><div className="cadm-checks"><label><input type="checkbox" checked={draft.firstOrderOnly} onChange={e=>setDraft({...draft,firstOrderOnly:e.target.checked,usageLimitPerUser:e.target.checked?1:draft.usageLimitPerUser,showOnHomepage:e.target.checked&&draft.audienceType==='PUBLIC'?draft.showOnHomepage:false})}/> First order only</label><label><input type="checkbox" checked={draft.showOnHomepage} disabled={!draft.firstOrderOnly||draft.audienceType!=='PUBLIC'} onChange={e=>setDraft({...draft,showOnHomepage:e.target.checked})}/> Feature on homepage</label><label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Active</label></div>
    {draft.audienceType==='ASSIGNED_USERS'&&<section className="cadm-audience"><b>Selected customers</b><div className="cadm-customer-search"><input value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="Search by name or email"/><button type="button" className="adm-btn" onClick={()=>void findCustomers()}>Find</button></div>{customers.map(c=><label key={c.id}><input type="checkbox" checked={draft.assignedUserIds?.includes(c.id)} onChange={e=>setDraft({...draft,assignedUserIds:e.target.checked?[...(draft.assignedUserIds||[]),c.id]:(draft.assignedUserIds||[]).filter(id=>id!==c.id)})}/><span>{c.firstName||c.first_name||''} {c.lastName||c.last_name||''}<small>{c.email}</small></span></label>)}<div className="madm-form-grid cadm-assignment-fields"><label className="adm-field"><span>Uses for selected customers <small>blank = coupon default</small></span><input type="number" min="1" value={assignmentLimit??''} onChange={e=>{setAssignmentLimit(e.target.value?Number(e.target.value):null);setAssignmentDetailsTouched(true);}}/></label><label className="adm-field"><span>Refund ID <small>optional</small></span><input type="number" min="1" value={refundId??''} onChange={e=>{setRefundId(e.target.value?Number(e.target.value):null);setAssignmentDetailsTouched(true);}}/></label><label className="adm-field madm-span"><span>Assignment reason</span><input maxLength={255} value={assignmentReason} onChange={e=>{setAssignmentReason(e.target.value);setAssignmentDetailsTouched(true);}} placeholder="Refund goodwill, delivery delay, support recovery…"/></label></div></section>}
    <div className="cadm-preview"><b>Customer sees:</b> {draft.type==='FLAT'?`₹${draft.discountValue} off`:`${draft.discountValue}% off`}{draft.minOrderValue?` above ${money(draft.minOrderValue)}`:''} · {draft.firstOrderOnly?'first order only':`${draft.usageLimitPerUser} use(s) per customer`} · {draft.usageLimitGlobal??'unlimited'} total uses</div>{error&&<div className="qadm-error">{error}</div>}<div className="madm-modal-actions"><button type="button" className="adm-btn" onClick={()=>setEditing(null)}>Cancel</button><button className="adm-btn primary" disabled={saving}>{saving?'Saving…':'Save coupon'}</button></div></form></div>}
  </AdminBody></>;
}
